version: '2'

services:
  node:
    image: node:10.15.0
    container_name: app-react
    working_dir: /project
    restart: always
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - /Users/msuarez/Workspace/app-react/:/project